"""empty message

Revision ID: 66045515038a
Revises: 7f7668e19902
Create Date: 2024-03-23 07:27:33.443282

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '66045515038a'
down_revision = '7f7668e19902'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(), nullable=False))
        batch_op.drop_column('password_hash')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password_hash', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('_password')

    # ### end Alembic commands ###
